### ISSUE TITLE
About seed settings

### ISSUE THREAD

**Issue by wang-h** [haonan-li/TWM-metonymy-resolution#1]
Hi, could you give the seed values used in your paper?

Best.

**Comment by haonan-li** [comment]
I don't remember, the default value is 42.
But the result I reported in the paper is the ten runs average, and the standard deviation is small.
So maybe try 42.

**Comment by wang-h** [comment]
> I don't remember, the default value is 42. But the result I reported in the paper is the ten runs average, and the standard deviation is small. So maybe try 42.

THX! We got comparable results by using the seed as [1111, 2222, 3333, 42, ...]. Did you use similar settings?

**Comment by haonan-li** [comment]
Yes.

**Comment by haonan-li** [comment]
I think we can close this issue.

**Comment by haonan-li** [comment]
I think we can close this issue.
