### ISSUE TITLE
Start and End position in convert_examples_to_features

### ISSUE THREAD

**Issue by MaggieK410** [haonan-li/TWM-metonymy-resolution#3]
Hello, 
I was trying to replicate your code and ran into a question in the utils_metonymy.py file. When converting samples into features, the lines 175-185 are used to recalculate the start and end position on token level from the word level positions that are stored in the datasets (here example.start_position/end_position). However, these newly calculated positions are not, what is fed into the model. As I understand, in the lines 224 and 225 the original positions used (example.start_position instead of just start_position).  When doing it the same way, I am able to replicate the results reported in the paper, but I was wondering if it wouldn't be better to pass on the positions on token level?

**Comment by haonan-li** [comment]
We indeed passed on the positions on token level.
The lines 175-185 are only used to make sure we didn't shift the target word positions after pre-process.

**Comment by MaggieK410** [comment]
Could you maybe give me the lines, where the pre-processing is done? As far as I could tell, in run_metonymy_resolution.py in line 354 the train dataset is generated by calling the load_and_cache_examples in utils_metonymy.py. That function then used the convert_examples_to_features (line 130) to generate the features including the start and end positions. The examples that are passed on to that function are generated by _create_examples, which, if I'm not mistaken, simply reads in what is written in the datasets files. I seem to be missing something...

**Comment by haonan-li** [comment]
To your question:

> Could you maybe give me the lines, where the pre-processing is done? As far as I could tell, in run_metonymy_resolution.py in line 354 the train dataset is generated by calling the load_and_cache_examples in utils_metonymy.py. That function then used the convert_examples_to_features (line 130) to generate the features including the start and end positions. The examples that are passed on to that function are generated by _create_examples, which, if I'm not mistaken, simply reads in what is written in the datasets files. I seem to be missing something...

Answer:

> _creat_examples is a data file reader, belong to class `WordClassificationProcessor`, this class was initialized in line 116 or 233. After initializing the `processor`, it read the file and create `examples`, then we use `convert_examples_to_features` to create features.

**Comment by MaggieK410** [comment]
Okay thank you!
